backend:
  name: git-gateway
  branch: master

media_folder: 'src/images/uploads'

collections:
  - label: 'Slider'
    name: 'slider'
    files:
      - label: 'slide'
        name: 'slide'
        file: '_content/slides.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: decription, widget: markdown }
          - { label: Image, name: slide-image, widget: 'image' }
